PaliwoMVC/Models/Paliwo.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaliwoMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PaliwoEntities : DbContext
    {
        public PaliwoEntities()
            : base("name=PaliwoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Paliwo> Paliwo { get; set; }
    }
}

PaliwoMVC/Models/Paliwo.Designer.cs
// T4 code generation is enabled for model 'E:\C#\PaliwoMVC\PaliwoMVC\Models\Paliwo.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

PaliwoMVC/Models/Paliwo.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaliwoMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paliwo
    {
        public int Id { get; set; }
        public Nullable<double> Kilometry { get; set; }
        public Nullable<double> Spalanie { get; set; }
        public Nullable<int> Osoby { get; set; }
        public bool DwieStrony { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<double> Cena { get; set; }
    }
}

PaliwoMVC/Models/Paliwo1.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

PaliwoMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PaliwoMVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

PaliwoMVC/Controllers/PaliwoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PaliwoMVC.Models;

namespace PaliwoMVC.Controllers
{
    public class PaliwoController : Controller
    {
        private PaliwoEntities db = new PaliwoEntities();

        // GET: Paliwo
        public ActionResult Index()
        {
            var paliwo = db.Paliwo.ToList().OrderByDescending(n => n.Data).Take(20);
            /*var paliwo2 = from n in paliwo
                          orderby n.Data descending
                          select n*/
            return View(paliwo);
        }


        public ActionResult Obliczanie(int? id)
        {
            var paliwoInDb = db.Paliwo.SingleOrDefault(p => p.Id == id);
            if (paliwoInDb == null)
                return View();

            return View(paliwoInDb);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Form(Paliwo paliwo)
        {
            if (!ModelState.IsValid)
                return View("Obliczanie", paliwo);

            paliwo.Data = DateTime.Now;
            db.Paliwo.Add(paliwo);
            db.SaveChanges();
            paliwo = db.Paliwo.ToList().Last();

            var wynik = (paliwo.Kilometry * paliwo.Spalanie) / 100;
            wynik *= paliwo.Cena;
            wynik /= paliwo.Osoby;
            if (paliwo.DwieStrony)
                ViewBag.Wynik = $"{wynik * 2} zł";
            else
                ViewBag.Wynik = $"{wynik} zł";

            return View("Obliczanie", paliwo); ;
        }
    }
}

PaliwoMVC/Controllers/StoperController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PaliwoMVC.Controllers
{
    public class StoperController : Controller
    {
        // GET: Stoper
        public ActionResult Stoper()
        {
            return View();
        }
    }
}

PaliwoMVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

PaliwoMVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

PaliwoMVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

PaliwoMVC/Views/Paliwo/Index.cshtml
@model IEnumerable<PaliwoMVC.Models.Paliwo>
@{
    ViewBag.Title = "Index";
}

<h2>Dotychczasowe jazdy</h2>
<table class="table table-striped">
    <tr>
        <td>Kilometry</td>
        <td>Spalanie</td>
        <td>Ilość osób</td>
        <td>Cena paliwa</td>
        <td>Czy w dwie strony</td>
        <td>Data</td>
        <td></td>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(m => item.Kilometry)
            </td>
            <td>
                @Html.DisplayFor(m => item.Spalanie)
            </td>
            <td>
                @Html.DisplayFor(m => item.Osoby)
            </td>
            <td>
                @Html.DisplayFor(m => item.Cena)
            </td>
            <td>
                @Html.DisplayFor(m => item.DwieStrony)
            </td>
            <td>
                @Html.DisplayFor(m => item.Data)
            </td>
            <td>
                @Html.ActionLink("Użyj", "Obliczanie", new { id = item.Id })
            </td>
        </tr>
    }
</table>

PaliwoMVC/Views/Paliwo/Obliczanie.cshtml
@model PaliwoMVC.Models.Paliwo
@{
    ViewBag.Title = "Obliczanie";
}

<h2 align="center">Hajs za Paliwo</h2>

@using (Html.BeginForm("Form", "Paliwo"))
{
    <div class="form-group">
        @Html.LabelFor(a => Model.Kilometry)
        @Html.TextBoxFor(a => Model.Kilometry, new { @class = "form-control" })
        @Html.ValidationMessageFor(a => Model.Kilometry)
    </div>
    <div class="form-group">
        @Html.LabelFor(a => Model.Spalanie)
        @Html.TextBoxFor(a => Model.Spalanie, new { @class = "form-control" })
        @Html.ValidationMessageFor(a => Model.Spalanie)
    </div>
    <div class="form-group">
        @Html.LabelFor(a => Model.Cena)
        @Html.TextBoxFor(a => Model.Cena, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(a => Model.Osoby)
        @Html.DropDownListFor(a => Model.Osoby, new SelectList(new List<Int32> { 1, 2, 3, 4, 5 }), "Ilość osób", new { @class = "form-control" })
    </div>
    <div class="form-group checkbox">
        @Html.LabelFor(a => Model.DwieStrony)
        @Html.CheckBoxFor(m => Model.DwieStrony)
    </div>
    @Html.AntiForgeryToken()
    <button class="btn btn-group-lg btn-primary" type="submit">Przelicz</button>
    <div class="container">
        <h3>@ViewBag.Wynik</h3>
    </div>

    @section scripts{
        @*<script src="~/Scripts/jquery-3.2.1.js"></script>
            <script src="~/Scripts/jquery.validate.js"></script>
            <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>*@

    }
}

PaliwoMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @*<script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>*@
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Paliwo", "Index", "Paliwo", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Strona główna", "Index", "Paliwo")</li>
                    <li>@Html.ActionLink("Kalkulator", "Obliczanie", "Paliwo")</li>
                    <li>@Html.ActionLink("Stoper", "Stoper", "Stoper")</li>   
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

PaliwoMVC/Views/Stoper/Stoper.cshtml
@{
    ViewBag.Title = "Stoper";
}
<link href="~/Content/Stoper.css" rel="stylesheet" />

<h2>Stoper</h2>
<h3 id="stoper">0:0:0</h3>
<div id="container">
    <div id="box"></div>
</div>
<div>
    <button class="btn btn-primary" onclick="start()">start</button>
    <button class="btn btn-toolbar" onclick="stop()">stop</button>
    <button class="btn btn-warning" onclick="reset()">reset</button>
</div>

<script src="~/Scripts/Stoper.js"></script>